# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  # kademliaBootNodes:
  #   image: kadlab:latest # Make sure your Docker image has this name.
  #   ports:
  #     - 8000:8000
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 10s
  #   networks:
  #     kademlia_network:
  #       ipv4_address: 10.0.8.3

  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    # ports:
    #   - 7000:7000
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 60
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      kademlia_network:

networks:
  kademlia_network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.8.0/24
